name: Develop Check
on: push

jobs:
  front-end-check:
    name: Front End Check
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: npm
          cache-dependency-path: './package-lock.json'

      - name: Install Dependencies
        run: yarn install

      - name: StyleLint & Prettier
        run: yarn lint-check
